/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.TextMind.form;

import com.TextMind.entity.User;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author KHOA
 */
public class Home extends javax.swing.JLayeredPane {
	private Chat chat;
	private Menu_Left menu_left = new Menu_Left();
	private Menu_Right menu_right = new Menu_Right();

	/**
	 * Creates new form Home
	 */
	public Home() {
		initComponents();
		init();
	}

	private void init() {
		setLayout(new MigLayout("fillx, filly", "5[200!]12[fill, 100%]8[300!]5", "0[fill]0"));
		this.add(menu_left);
		chat = new Chat();
		this.add(chat);
		this.add(menu_right);
		chat.setVisible(false);
	}

	public void setUser(User user) {
		chat.setUser(user);
		chat.setVisible(true);
	}

	public Menu_Left getMenu_left() {
		return menu_left;
	}

	public void setMenu_left(Menu_Left menu_left) {
		this.menu_left = menu_left;
	}

	public Menu_Right getMenu_right() {
		return menu_right;
	}

	public void setMenu_right(Menu_Right menu_right) {
		this.menu_right = menu_right;
	}

	public Chat getChat() {
		return chat;
	}

	public void setChat(Chat chat) {
		this.chat = chat;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 915, Short.MAX_VALUE));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 561, Short.MAX_VALUE));
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	// End of variables declaration//GEN-END:variables
}
