/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.TextMind.component;

import static com.TextMind.Socket.SocketManager.getSocket;
import com.TextMind.event.PublicEvent;
import com.TextMind.swing.ScrollBar;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author ducan
 */
public class Reported_Infor extends javax.swing.JDialog {
	private String idTo, idFrom, detail;
	private int pX;
	private int pY;

	/**
	 * Creates new form NewJDialog
	 */
	public Reported_Infor(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		init();
		setLocationRelativeTo(null);
	}

	public void init() {
		ScrollBar sb = new ScrollBar();
		sp.setVerticalScrollBar(sb);
		txtIDfrom.setEditable(false);
		txtIDto.setEditable(false);
		txtDetail.setEditable(false);
		lblTitle.setText("INFORMATION");
		lblTitle.setFont(new Font("sansserif", 1, 30));
		lblTitle.setForeground(new Color(204, 255, 255));

		btnDelete.setBackground(new Color(0, 102, 204));
		btnDelete.setForeground(new Color(250, 250, 250));
		report.add(btnDelete, "w 40%, h 40");

		btnClose.setBackground(new Color(0, 102, 204));
		btnClose.setForeground(new Color(250, 250, 250));
		report.add(btnClose, "w 40%, h 40");
	}

	public void setInfor(String idFrom, String idTo, String detail) {
		txtIDfrom.setText(idFrom);
		txtIDto.setText(idTo);
		txtDetail.setText(detail);
		this.idFrom = idFrom;
		this.idTo = idTo;
		this.detail = detail;

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		report = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		btnDelete = new javax.swing.JButton();
		btnClose = new javax.swing.JButton();
		title2 = new javax.swing.JPanel();
		lblTitle = new javax.swing.JLabel();
		sp = new javax.swing.JScrollPane();
		txtDetail = new com.TextMind.swing.JIMSendTextPane();
		jLabel3 = new javax.swing.JLabel();
		txtIDfrom = new javax.swing.JTextField();
		txtIDto = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setUndecorated(true);

		report.setBackground(new java.awt.Color(153, 204, 255));

		jLabel1.setBackground(new java.awt.Color(255, 255, 255));
		jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel1.setText("DETAILS:");

		btnDelete.setText("Delete Account");
		btnDelete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDeleteActionPerformed(evt);
			}
		});

		btnClose.setText("Close");
		btnClose.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCloseActionPerformed(evt);
			}
		});

		title2.setBackground(new java.awt.Color(102, 153, 255));
		title2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				title2MouseDragged(evt);
			}
		});
		title2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				title2MousePressed(evt);
			}
		});

		lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lblTitle.setText("...");

		javax.swing.GroupLayout title2Layout = new javax.swing.GroupLayout(title2);
		title2.setLayout(title2Layout);
		title2Layout.setHorizontalGroup(
				title2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(lblTitle,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		title2Layout.setVerticalGroup(title2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE));

		sp.setViewportView(txtDetail);

		jLabel3.setBackground(new java.awt.Color(255, 255, 255));
		jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel3.setText("FROM");

		jLabel4.setBackground(new java.awt.Color(255, 255, 255));
		jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(255, 255, 255));
		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel4.setText("TO");

		javax.swing.GroupLayout reportLayout = new javax.swing.GroupLayout(report);
		report.setLayout(reportLayout);
		reportLayout.setHorizontalGroup(reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(title2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(reportLayout.createSequentialGroup().addContainerGap()
						.addGroup(reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(reportLayout.createSequentialGroup().addGap(0, 206, Short.MAX_VALUE)
										.addComponent(btnDelete).addGap(18, 18, 18).addComponent(btnClose))
								.addComponent(sp, javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(reportLayout.createSequentialGroup().addComponent(jLabel1).addGap(0, 0,
										Short.MAX_VALUE))
								.addGroup(reportLayout.createSequentialGroup().addComponent(jLabel3).addGap(17, 17, 17)
										.addComponent(txtIDfrom))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										reportLayout.createSequentialGroup().addComponent(jLabel4)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37,
														Short.MAX_VALUE)
												.addComponent(txtIDto, javax.swing.GroupLayout.PREFERRED_SIZE, 355,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap()));
		reportLayout.setVerticalGroup(reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(reportLayout.createSequentialGroup()
						.addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(txtIDfrom, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel4).addComponent(txtIDto, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(28, 28, 28).addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, 192,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(33, 33, 33)
						.addGroup(reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(btnClose).addComponent(btnDelete))
						.addContainerGap(17, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				report, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				report, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteActionPerformed
		// TODO add your handling code here:
		getSocket().emit("banUser", idTo);
		PublicEvent.getInstance().getEventMenuLeft().unShowBanned(idTo);
		this.dispose();
	}// GEN-LAST:event_btnDeleteActionPerformed

	private void title2MouseDragged(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_title2MouseDragged
		this.setLocation(this.getLocation().x + evt.getX() - pX, this.getLocation().y + evt.getY() - pY);
	}// GEN-LAST:event_title2MouseDragged

	private void title2MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_title2MousePressed
		pX = evt.getX();
		pY = evt.getY();
	}// GEN-LAST:event_title2MousePressed

	private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCloseActionPerformed
		this.dispose();
	}// GEN-LAST:event_btnCloseActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Reported_Infor.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Reported_Infor.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Reported_Infor.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Reported_Infor.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				Reported_Infor dialog = new Reported_Infor(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnClose;
	private javax.swing.JButton btnDelete;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel lblTitle;
	private javax.swing.JPanel report;
	private javax.swing.JScrollPane sp;
	private javax.swing.JPanel title2;
	private com.TextMind.swing.JIMSendTextPane txtDetail;
	private javax.swing.JTextField txtIDfrom;
	private javax.swing.JTextField txtIDto;
	// End of variables declaration//GEN-END:variables
}
